require 'minitest/autorun'
require 'cobertura_xml_merger'

describe CoberturaXmlMerger::Merger do
  before do
    @merger = CoberturaXmlMerger::Merger.new
  end

  describe '#merge_xml' do
    before do
      @xml1 = <<-EOF
        <!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
        <!-- Generated by simplecov-cobertura version 1.1.0 (https://github.com/dashingrocket/simplecov-cobertura) -->
        <coverage line-rate='0.77' branch-rate='0' lines-covered='5041' lines-valid='6570' branches-covered='0' branches-valid='0' complexity='0' version='0' timestamp='1474916200'>
        <sources>
          <source>/Users/juancastaneda/Projects/efficiency</source>
        </sources>
        <packages>
          <package name='efficiency' line-rate='0.77' branch-rate='0' complexity='0'>
            <classes>
              <class name='accounts_controller' filename='app/controllers/accounts_controller.rb' line-rate='1.0' branch-rate='0' complexity='0'>
                <methods/>
                <lines>
                  <line number='8' branch='false' hits='1'/>
                </lines>
              </class>
              <class name='sessions_controller' filename='app/controllers/sessions_controller.rb' line-rate='1.0' branch-rate='0' complexity='0'>
                <methods/>
                <lines>
                  <line number='10' branch='false' hits='2'/>
                </lines>
              </class>
              <class name='unique_controller' filename='app/controllers/unique_controller.rb' line-rate='1.0' branch-rate='0' complexity='0'>
                <methods/>
                <lines>
                  <line number='2' branch='false' hits='0'/>
                </lines>
              </class>
            </classes>
          </package>
        </packages>
      EOF
      @xml2 = <<-EOF
        <!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
        <!-- Generated by simplecov-cobertura version 1.1.0 (https://github.com/dashingrocket/simplecov-cobertura) -->
        <coverage line-rate='0.77' branch-rate='0' lines-covered='5041' lines-valid='6570' branches-covered='0' branches-valid='0' complexity='0' version='0' timestamp='1474916200'>
        <sources>
          <source>/Users/juancastaneda/Projects/efficiency</source>
        </sources>
        <packages>
          <package name='efficiency' line-rate='0.77' branch-rate='0' complexity='0'>
            <classes>
              <class name='accounts_controller' filename='app/controllers/accounts_controller.rb' line-rate='1.0' branch-rate='0' complexity='0'>
                <methods/>
                <lines>
                  <line number='8' branch='false' hits='0'/>
                </lines>
              </class>
              <class name='sessions_controller' filename='app/controllers/sessions_controller.rb' line-rate='1.0' branch-rate='0' complexity='0'>
                <methods/>
                <lines>
                  <line number='10' branch='false' hits='1'/>
                </lines>
              </class>
              <class name='another_controller' filename='app/controllers/another_controller.rb' line-rate='1.0' branch-rate='0' complexity='0'>
                <methods/>
                <lines>
                  <line number='1' branch='false' hits='1'/>
                </lines>
              </class>
            </classes>
          </package>
        </packages>
      EOF
    end

    it 'should add line hits' do
      merged_xml = @merger.merge_xml(@xml1, @xml2)
      merged_xml.must_match %r{<line number="8"[^>]+hits="1"/>}
      merged_xml.must_match %r{<line number="10"[^>]+hits="3"/>}
    end

    it 'should keep classes only ocurring in one file' do
      merged_xml = @merger.merge_xml(@xml1, @xml2)
      merged_xml.must_match %r{<class name="another_controller"[^>]+>}
      merged_xml.must_match %r{<line number="1"[^>]+hits="1"/>}

      merged_xml.must_match %r{<class name="unique_controller"[^>]+>}
      merged_xml.must_match %r{<line number="2"[^>]+hits="0"/>}
    end
  end
end
